### ISSUE TITLE
chats moved to  group exists twice after restarting pidgin

### ISSUE THREAD

**Issue by gzuaps** [EionRobb/purple-teams#10]
Hi @EionRobb ,
Thanks for this plugin it is so far working well.
As in the description, I create groups to tidy up my buddy list.
If I move a teams chat into a group then when I restart pidgin it exists twice, both in the new group and its original location.
I also use the purple-slack plugin and it behaves as expected.

Hope this makes sense.
Regards.

**Comment by EionRobb** [comment]
Whoops, sorry about that.  Hopefully the above commit helps make that not happen.
