### ISSUE TITLE
Tenant ID might not end with ".onmicrosoft.com"

### ISSUE THREAD

**Issue by blu256** [EionRobb/purple-teams#13]
The tenant ID of the Teams group I am part of does not end with  ".onmicrosoft.com", so I had to modify the source code to be able to log in.

Maybe a checkbox would be a better idea than hard-coding this value?

**Comment by EionRobb** [comment]
Sorry for the delay, just looking over this issue now.  Were you using a GUID as the tenant ID or a domain name?  At the moment the plugin detects if you're using a domain (well, it checks for `.`) but doesn't look for GUIDs at the moment

**Comment by KangarooWasp** [comment]
I am not the original person (and i don't currently have this plugin installed) but i came across this repo this evening. My tenant ID is a GUID, I suppose that means I wouldn't be able to use this plugin unless it is updated to fix this?

**Comment by EionRobb** [comment]
I'll add support for this in now :)

**Comment by EionRobb** [comment]
Give that a try and see how it goes?

**Comment by blu256** [comment]
Hello, the tenant ID was a GUID indeed. Unfortunately that group is no longer active so I don't think I can test the change. The code changes seem valid and the regexp does match that old group GUID (I checked via `.purple/accounts.xml`) so I think it will might okay. :+1:

**Comment by EionRobb** [comment]
Hopefully @KangarooWasp can confirm :)

**Comment by KangarooWasp** [comment]
i think it worked? it accepted my guid and let me log in
