### ISSUE TITLE
No notification sounds

### ISSUE THREAD

**Issue by poetimp** [EionRobb/purple-teams#15]
I have been using this for several days and have realized that there are no sounds generated when a new message comes in or a new conversation is started. Not a big deal but I have missed a few messages because I am trained to respond to the sounds like pavlov's dogs :)

**Comment by NoTuxNoBux** [comment]
Is it possible that there are also no notifications at all? I'm using `pidgin-notify+` for the Steam plug-in and others, where it works fine, but it doesn't seem to react to messages coming in from Teams.

**Comment by EionRobb** [comment]
Did it magically resolve for you too, @poetimp ?

**Comment by EionRobb** [comment]
Just cleaning up old issues and saw that this one was from almost 2 years ago.  Please don't hesitate to reopen this issue if it's still a problem :)
