### ISSUE TITLE
Teams for Personal Accounts

### ISSUE THREAD

**Issue by TechnoSwiss** [EionRobb/purple-teams#16]
Been thinking about switching from Skype to Teams Personal, but would love to stick with Pidgin for that. Thoughts on what would be required to get this working with a personal account? I'm getting the "Guest user OID is missing. User is not redeemed. (code 0)" error, but I'm guessing that's because I don't know/have a tenant to enter.

**Comment by ecxod** [comment]
I tested it also, it is not working I get : `Login error: Guest user OID is missing. User is not redeemed. (code 0)`

**Comment by niutech** [comment]
If you want to add support for MS Teams Personal (free), have a look at the [unofficial API](https://techcommunity.microsoft.com/t5/teams-developer/how-to-use-microsoft-teams-free-chat-api/m-p/3839870/highlight/true#M7843) which I am using in my [Krak Bot](https://github.com/niutech/krak-bot) chat bot, as well as the [user enumeration in MS Teams Personal](https://www.securesystems.de/blog/a-fresh-look-at-user-enumeration-in-microsoft-teams/) and [MessagingAPIService.json](https://gist.github.com/ardatan/a4a619d6d1a4daa3b65287d0298e50e0).

**Comment by EionRobb** [comment]
There's a first cut of a Teams personal/free in the above commit if anyone's interested in trying it.  (or https://github.com/EionRobb/purple-teams/actions/runs/7948474584/artifacts/1254441417 for Windows people)

It shows up as a separate protocol in the dropdown list as there's some subtle differences between the two, including a different authentication client id.
![image](https://github.com/EionRobb/purple-teams/assets/1063865/95595571-b2c8-43b8-aff4-b29b68e96a8e)

I've only tested out the bare basics of sending a few one-to-one IMs to myself, so would appreciate some feedback of things that need improving :)

**Comment by niutech** [comment]
@EionRobb I can confirm Teams Personal works in Windows 10! However, it doesn't download any user names (only IDs) until I restart Pidgin:

![Purple-Teams](https://github.com/EionRobb/purple-teams/assets/384997/31323d55-5c8b-45aa-ac54-a62e3c46d52b)

Also the list of rooms is cryptic, showing only IDs:

![image](https://github.com/EionRobb/purple-teams/assets/384997/a670ec52-8344-468f-986d-0bf271f29928)

But the greatest thing is that this Teams client takes only 15 MB of RAM instead of hundreds MB! Well done, thank you!

**Comment by niutech** [comment]
A major issue: I cannot send a message from Pidgin directly to a buddy in Teams (live:.cid.xxxxxxxxxx), I have to open a chat room with me & him (19:uni01_xxxxxxxxxxxxxxxxxxxx@thread.v2) and type my message there. This is counter intuitive.

**Comment by EionRobb** [comment]
Ah! I hadn't tried sending any new outgoing messages, only replying to incoming. 

Those 2 issues you describe might be interrelated though, there's different ways of detecting a one-to-one chat to what's in the Teams for Work, and it doesn't sound like it's linking the chat room up with the contact properly. Fingers crossed solving one solves the other!

**Comment by EionRobb** [comment]
I believe sending messages on Teams Personal accounts works ok now, as of a few commits ago?  Please feel free to reopen this issue if it's still a problem

**Comment by theultramage** [comment]
Just noting that the github readme still lists this as unsupported / wip (with a reference to this issue).

**Comment by EionRobb** [comment]
Oh yeah, thanks for the pointer @theultramage 😄
