### ISSUE TITLE
Can't start private chat due to invalid 'mri'

### ISSUE THREAD

**Issue by ivy-rew** [EionRobb/purple-teams#2]
I've just tried to start a private chat conversion, but it seems as if I'm not able to send text-messages via ms-teams plugin.
The chat window will print an error stating: `(08:41:03 AM) Conversation Mri is not valid mri for a conversation!`

The debug logs while doing this look like this: though I can't see anything related to 'MRI' in it.
Can you make sense of it?
[purple-debug-Mri-isNotValid.log](https://github.com/EionRobb/purple-teams/files/8486871/purple-debug-Mri-isNotValid.log)
[purple-debug-mri.log](https://github.com/EionRobb/purple-teams/files/8486872/purple-debug-mri.log)

Maybe indeed, as you pointed out earlier, the 'apac' teams server instances could be a problem. I'm located in western europe (Switzerland).

**Comment by EionRobb** [comment]
Ah, a major difference between skype and teams is that every chat in teams is a group chat, including the DM's

I need to add in a way to start a new DM, as well as detect that incoming chats are DMs or not :)

**Comment by ivy-rew** [comment]
Yes, you are right. As the day starts and more and more chats are being initiated I can read and respond with pidgin to incoming requests
![pidginTeams](https://user-images.githubusercontent.com/15085693/163347821-d52bd3a9-370d-4b05-9e55-2e8b520bee02.png)

It's, that just that I can't initiate not yet existing direct message chats on my own.

**Comment by EionRobb** [comment]
I've just committed the beginnings of being able to do DMs - its a bit weird, but:  the first DM you send gets eaten up as it tries to create the DM conversation in the background, and then after that point all the DM messages go to that window and can be sent from there

Ever so slightly improved on the existing, but still a bit more to go :)

**Comment by ivy-rew** [comment]
I've just pulled your change, re-built it using `make` and added libteams.so to my pidgin plugins dir.
But now pidgin crashes after booting. It seems as if the code fails after running through the login procedure:
```
rew@zuglinrew:/mnt/data/dev/projects/purple-teams$ pidgin

(Pidgin:1182591): Json-CRITICAL **: 13:42:27.906: json_node_set_array: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_ARRAY' failed

(Pidgin:1182591): Json-CRITICAL **: 13:42:27.906: json_object_get_members_internal: assertion 'object != NULL' failed
Segmentation fault (core dumped)
rew@zuglinrew:/mnt/data/dev/projects/purple-teams$ pidgin -v
Pidgin 2.13.0 (libpurple 2.13.0)
```

**Comment by EionRobb** [comment]
Whoops. Sorry about that. Can you get a backtrace: https://developer.pidgin.im/wiki/GetABacktrace

**Comment by EionRobb** [comment]
I think I might have found the cause of the crash

**Comment by ivy-rew** [comment]
Yes, you got this. Thanks a lot. Now I have named discussions groups :love_letter: 
And as it seems, the online status is working too.
Furthermore the 'mri' error is gone. Gone check next Tuesday when my colleagues are back how the experience with initiating chats is.

**Comment by ivy-rew** [comment]
Today my colleagues are back, and somehow my pidgin starts crashing again.
However, when trying to get a backtrace this doesn't happen. But pidgin is also in a strange state when started via gpd. I can't really click anything in the UI.
Hopefully that log helps anyway?
[pidgin-backtrace.log](https://github.com/EionRobb/purple-teams/files/8510938/pidgin-backtrace.log)

**Comment by EionRobb** [comment]
Ah, that backtrace was helpful, thanks.

I had forgotten about those 'notification' messages that come through - they're coming through as a message but not like any other message.  I've got them to not crash in that last commit, but they aren't yet displaying.

**Comment by ivy-rew** [comment]
Yes, you nailed it. Pidgin is no longer crashing :love_letter: :bird: 
Thanks a lot: I'll come back with more feedback in new issues ;-)
