### ISSUE TITLE
Possible issues with Spectrum2

### ISSUE THREAD

**Issue by qstambaugh** [EionRobb/purple-teams#20]
I tried signing in through Spectrum2. When I enter in my account name, I don't get any feedback indicating it failed or succeeded. I only have a personal Teams account, not a Work or School one, so that might be the issue. I skimmed through the logs, but nothing really stood out to me with my limited knowledge.

[spectrum2.log](https://github.com/EionRobb/purple-teams/files/9124761/spectrum2.log)

**Comment by EionRobb** [comment]
Ah. There's no support for teams for personal yet. See issue #16

**Comment by qstambaugh** [comment]
Ah okay, thank you
