### ISSUE TITLE
Support displaying Giphy GIFs/videos

### ISSUE THREAD

**Issue by NoTuxNoBux** [EionRobb/purple-teams#23]
The popular Giphy plug-in for Teams allows posting GIFs, I'm not sure if Pidgin allows displaying animated content, but it would be nice to also be able to view these in Pidgin.

Looking at the Giphy site, the "GIF's" are often actually MP4 videos using a `video` tag.

**Comment by ivy-rew** [comment]
Yes, would be cool to see the GIFs getting posted by team-mates ... yet I only see an empty line for these. 
![giphy](https://user-images.githubusercontent.com/15085693/191963759-51cd5b25-6c0c-41ec-8527-5f556be82e47.png)

Just posting the link to these GIFs would be totally acceptable ... this is what microsoft does too, if privacy -> optional connected experiences is disabled.
![giphyDisabled](https://user-images.githubusercontent.com/15085693/191964196-d752b2e0-b4f6-4927-9fb4-d9ae6add1d3a.png)

**Comment by EionRobb** [comment]
Hopefully fixed by https://github.com/EionRobb/purple-teams/commit/7662c794e701cbb93841c1af29d2d08b4f91417d ?

**Comment by NoTuxNoBux** [comment]
An initial test seems to work mostly from my end:

![afbeelding](https://user-images.githubusercontent.com/73220431/201864688-5555e4d7-aead-497f-a28b-94bb61a4c318.png)

![Screenshot](https://user-images.githubusercontent.com/73220431/201864892-8bc9d9c1-7bdd-4ee8-b287-6a015f136a39.png)

"Click here" opens the GIF in the browser, and then there is a second link to the same GIF, with a broken icon underneath it.

**Comment by ivy-rew** [comment]
GIF's work great on my side. Didn't know that Stickers are something technically different .. they are shown as link, but the link doesn't work. ... however, here Stickers are rarely used and GIFs are popular. So I personally don't mind :-)
![gifsInPidgin](https://user-images.githubusercontent.com/15085693/201872350-bc09e786-5d1c-4e52-a88e-fde54f7230cb.png)



Thanks a lot for the improvement @EionRobb

**Comment by EionRobb** [comment]
Stickers are different again?!? Argh 😄 

Ok will try out some stickers tomorrow and see what they look like. Hopefully there's a more generic way for both to work, along with inline images.

**Comment by EionRobb** [comment]
I tried posting a few stickers to see what would happen but they all show up fine. I did note that if I send them the links show up as incoming messages, and plays the wrong sounds though. Latest commit foxes that. 

Is it possible to re-test to see if it was just a one-off glitch?

**Comment by NoTuxNoBux** [comment]
I think it might indeed have been:

![afbeelding](https://user-images.githubusercontent.com/73220431/202441505-f02bba75-969b-4a3b-8fa8-ecf2f7fd902c.png)

![afbeelding](https://user-images.githubusercontent.com/73220431/202441477-2ca2e1cb-ac78-4dcc-a74b-705770f88b1b.png)

I no longer see the tiny missing icon, but I don't see any image showing up at all like @ivy-rew does. Does this need some sort of additional setting or Pidgin plug-in to work?

**Comment by EionRobb** [comment]
There's a "Conversation Colors" plugin that's known to eat inline images. If you have that enabled, try disabling it

**Comment by NoTuxNoBux** [comment]
Hmmm, I have it installed, but not enabled. Would inspecting debug logs work to help me/you pinpoint why this is happening? :sweat_smile:

**Comment by NoTuxNoBux** [comment]
Update: I updated to latest master today, received some other GIFs, and they work :tada: . For some reason it's just the GIFs I post to myself on Teams that (still) have this problem.

**Comment by EionRobb** [comment]
Just cleaning out old issues and found that this one seems to be sorted but was still open.  If anyone still has issues with giphy gifs, please don't hesitate to open a new issue :)
