### ISSUE TITLE
Contact status doesn't seem to update (sometimes?)

### ISSUE THREAD

**Issue by NoTuxNoBux** [EionRobb/purple-teams#25]
I turned Pidgin on when I was in a meeting with some colleagues, where it correctly displayed they were "busy". After leaving the meeting, their status never changed from "busy" back to "available" until I restarted Pidgin. Is it possible that status updates are not handled or polled for yet?

**Comment by EionRobb** [comment]
Ah. Status updates only get set during login at the moment. I've been trying to implement the status event stream but it's a bit weird. In the mean time i should make the regular one on a polling loop... Better than nothing 


Just to document here what needs to happen for the real status updates, there's a "reverse webhook" that needs to be set up, over a websocket, it gets sent push notifications from the Teams server as url requests embedded in websocket json payloads

**Comment by EionRobb** [comment]
For now, I've added in a 5-minute polling refresh.  I was hoping I'd have found some time to switch to the websockets live status updates stuff by now, but that silly life thing gets in the way 

Should be kinda working in https://github.com/EionRobb/purple-teams/commit/55bfc0ba680434c0c53a393d89f110c7a2ada417 if you'd like to give that a try :)

**Comment by NoTuxNoBux** [comment]
For me everyone seems to be permanently offline with latest master :smile: .

**Comment by EionRobb** [comment]
Well then that's less than ideal! 😂 
Whoops! 

I'll have a look at it again. I think that can happen if we ask for status updates for too many people at once or if there's one person who is unknown in the list of people we're getting updates for.

**Comment by NoTuxNoBux** [comment]
It seems to have magically resolved itself again :sweat_smile: . Yesterday all my contacts remained offline whilst I could see in Teams that they were not so, but today they seem to get their appropriate status.

**Comment by EionRobb** [comment]
I like magic!
