### ISSUE TITLE
"The refresh token has expired or is invalid due to sign-in frequency checks by conditional access"

### ISSUE THREAD

**Issue by pkar70** [EionRobb/purple-teams#26]
Seems like token expiration, but no relogin (no login dialog shown).

Probably same as https://github.com/Azure/azure-cli/issues/17714 , as full error text is:
"AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2022-07-30T19:55:21.1057795Z and the maximum allowed lifetime for this request is 1209600.
Trace ID: edd8cefa-bc52-4bdf-8aaa-ca1b30864300
Correlation ID: 8a6818d1-764e-4767-9fcc-b2072bab4697
Timestamp: 2022-08-15 09:33:09Z"

**Comment by EionRobb** [comment]
Same as https://github.com/EionRobb/purple-teams/issues/19 ?

**Comment by EionRobb** [comment]
Ok, not quite the same issue as #19, but should be same error handling (clear out 'password' in accounts.xml)

**Comment by pkar70** [comment]
No, I didn't change password... I will try clearing out 'password' in accounts.xml)

**Comment by EionRobb** [comment]
So is it all ok now, or still broken?

**Comment by pkar70** [comment]
I can login, so this is OK.
Sometimes new chat (chat with person I didn't chat before), initiated by other person (not by me) is opened as "19:xxxxxx" (very long name), without user name, and I cannot reply to this in Pidgin, but this is another story and can be "work-arounded".

**Comment by EionRobb** [comment]
OK Cool, glad the login bit is working for you :)

If you could open a new issue (if there isn't one already) for the "19:..." user ids that would be awesome :)
