### ISSUE TITLE
Using purple-teams in bitlbee via libpurple?

### ISSUE THREAD

**Issue by gardar** [EionRobb/purple-teams#30]
Anyone managed to get this plugin working with bitlbee?

I installed the plugin and I can see that it's enabled when I enter `purple help`.

```
@root | BitlBee libpurple module supports the following IM protocols:
@root |
@root | * bonjour (Bonjour)
@root | * gg (Gadu-Gadu)
@root | * novell (GroupWise)
@root | * hangouts (Hangouts)
@root | * irc (IRC)
@root | * matrix (Matrix)
@root | * simple (SIMPLE)
@root | * skypeweb (Skype (HTTP))
@root | * slack (Slack)
@root | * eionrobb-msteams (Teams)
@root | * jabber (XMPP)
@root | * zephyr (Zephyr)
```

I tried adding my account with:
`account add eionrobb-msteams myuser@my.org`

But when I try to activate the account I just get a connection timeout and no helpful errors.

`account on eionrobb-msteams`

```
eionrobb-msteams - Login error: Connection timeout
eionrobb-msteams - Logging in: Signing off..
eionrobb-msteams - Logging in: Reconnecting in 5 seconds..
eionrobb-msteams - Login error: Connection timeout
eionrobb-msteams - Logging in: Signing off..
eionrobb-msteams - Logging in: Reconnecting in 15 seconds..
eionrobb-msteams - Login error: Connection timeout
eionrobb-msteams - Logging in: Signing off..
```

**Comment by gardar** [comment]
Update: I am able to successfully connect with bitlbee.
It turns out that when I set the account on I receive a private message from `purple_request_0` for the authentication, I just didn't see it before.

Now on to the next issue.
Users and groups don't get "human friendly" names so that this is not really usable at the moment. Is that something that could be fixed in the plugin @EionRobb or would it require a helper script in the client (I remember having to use such a helper script for facebook in the past).

**Comment by EionRobb** [comment]
Did you manage to find the bitlbee account setting for that?  Something along the lines of `account set nick_format %full_name`?

**Comment by 7kilobytes** [comment]
> Update: I am able to successfully connect with bitlbee. It turns out that when I set the account on I receive a private message from `purple_request_0` for the authentication, I just didn't see it before.
> 
What did you do when you received the privat message and open the link?

**Comment by gardar** [comment]
> Did you manage to find the bitlbee account setting for that? Something along the lines of `account set nick_format %full_name`?

Thanks for the hint, I wasn't aware I could set the nick format like that in bitlbee, using that setting works great for one on one chats, but group(team) chats are still not human friendly. I guess I'd need a way to set the nick_format for both persons and groups.



> > Update: I am able to successfully connect with bitlbee. It turns out that when I set the account on I receive a private message from `purple_request_0` for the authentication, I just didn't see it before.
> 
> What did you do when you received the privat message and open the link?

Basically the same as I would do in pidgin, click the link and log in and then copy the url I get redirected and paste it back into the private message.
Be aware that the url is quite long and you need to make sure your irc client doesn't split it into two messages.

**Comment by cwegener** [comment]
>  Be aware that the url is quite long and you need to make sure your irc client doesn't split it into two messages.

I am actually stuck myself at this stage ... I can't figure out how to tell WeeChat to not split my message with the response URL into three messages ... might have to just bypass WeeChat for the initial login

**Comment by gardar** [comment]
I'm actually using weechat myself, you can simply increase the size of `split_msg_max_length` either globally with `irc.server_default.split_msg_max_length` or `irc.server.bitlbee.split_msg_max_length`

**Comment by cwegener** [comment]
> `split_msg_max_length`

Awesome! That works. Not sure how I didn't find that option.

Time to explore a bit more of the functionality now.

**Comment by gardar** [comment]
One issue I've noticed, when I disconnect from bitlbee (when restarting etc.) I need to re-login by opening the link whereas pidgin will log me in automatically after exiting.
Not sure if it has something to do with my bitlbee server, do you face the same issue @cwegener ?

**Comment by cwegener** [comment]
> One issue I've noticed, when I disconnect from bitlbee (when restarting etc.) I need to re-login by opening the link whereas pidgin will log me in automatically after exiting. Not sure if it has something to do with my bitlbee server, do you face the same issue @cwegener ?

I see exactly the same behaviour myself. Pidgin does not ask for another interactive login after a restart, but bitlbee does.
I wonder how purple-teams stores the refresh token.

**Comment by EionRobb** [comment]
Hopefully that commit makes the refresh token save on bitlbee without needing to re-auth all the time. :)

I'm looking at whether to switch over to a nicer way of doing auth that won't need anything keyed in to a prompt, but a little bit more work to get there (just documented it for now)

**Comment by cwegener** [comment]
> Hopefully that commit makes the refresh token save on bitlbee without needing to re-auth all the time. :)
> 
> I'm looking at whether to switch over to a nicer way of doing auth that won't need anything keyed in to a prompt, but a little bit more work to get there (just documented it for now)

Yup. That makes the refresh token persist after signing out of bitlbee

**Comment by fast-90** [comment]
@gardar @cwegener have you found a way to search for people based on their names and/or e-mail address? For me, the "handle" for other people is of the format `org:id-[long-number]`, and whilst I can make it display it properly with `nick_format`, it's a pain to try to add people who are not in my contact list yet. 

In Pidgin, I am able to do this by using going to Accounts -> Search friend and then typing in the name. Is this possible with Bitlbee at all?

**Comment by EionRobb** [comment]
Just doing a bit of housekeeping, so closing this one off as the original issue reported is ok.  I've also changed the authentication URL around to be a shorter one, so there shouldn't be any issues with message length now.
