### ISSUE TITLE
How to get it to work?

### ISSUE THREAD

**Issue by lhpitn** [EionRobb/purple-teams#31]
Hi,

i (on windows 10 64-bit) downloaded 

https://eion.robbmob.com/libteams.dll

put it into 

%APPDATA%\.purple\plugins

restarted Pidigin (Pidgin 2.14.10 (libpurple 2.14.10)) but the plugin dosn’t show up, neither as protocol when adding a new account nor in the plugin list...

thanks for your help in advance

**Comment by EionRobb** [comment]
You'll also need libjson-glib-1.0.dll in the Pidgin folder (not the Pidgin\plugins folder) if you've not already got that 

If you do have json-glib, then can you get a plugin debug by opening up the debug log (from the Buddy List->Help->Debug Window) then leave that open as you reload the plugins list (Tools->Plugins) then close the plugins window and copy-paste the output of the debug window here

**Comment by EionRobb** [comment]
Did you have any luck?
