### ISSUE TITLE
Login when MFA is required does not work

### ISSUE THREAD

**Issue by JimPatterson** [EionRobb/purple-teams#39]
When trying to login using an account where MFA is required, I get:

> AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access ...

I was able to work around this my adding `amr_values=ngcmfa` to the initial request for the OAuth authorize request.
See https://stackoverflow.com/questions/57112079/azure-active-directory-multi-factor-check-for-authorization for where I found this solution.

I'm not sure how you could know that you need to include it?  Maybe a new flag on the account that says MFA needed?

Anyway, thanks for writing this and all the other plugins you have done.

**Comment by EionRobb** [comment]
Thanks for the helpful info!  Don't suppose you've seen whether just the "use MFA if available" option would work?  It doesn't seem to be documented, but might behave better than forcing MFA on (especially for those brave enough to not have MFA on their accounts)

**Comment by JimPatterson** [comment]
I encountered a scenario where I could test the "use MFA if available" flag, and it worked like a charm.  Without the flag, it failed, with the flag, it asked for the MFA.  I can't test what happens when you don't have MFA, but for people with MFA, it works.

**Comment by EionRobb** [comment]
So I added into the plugin `&amr_values=mfa` did that work or does it only work with `amr_values=ngcmfa`?

**Comment by EionRobb** [comment]
WFM :)
