### ISSUE TITLE
Buddies from Teams all show as Offline (when they're not)

### ISSUE THREAD

**Issue by jpatrick327** [EionRobb/purple-teams#40]
Newbie here. I apologize if this is not the correct place to report what is likely a PICNIC (user) error.  I'm sure I'm just missing a config setting somewhere, but all buddies from my Teams client are reporting as Off-line. Any guidance?

**Comment by EionRobb** [comment]
I've added in a new way of getting presence updates from the server using a websocket.  Unfortunately I never experienced the buddies showing as offline bug so don't know if that helps the problem at all. Are you able to try with the latest version and see if it still has that problem?

**Comment by zzavadil** [comment]
Hi, for me it works correctly now, thanks!
