### ISSUE TITLE
Messages now show "Files sent:" at the end

### ISSUE THREAD

**Issue by greatquux** [EionRobb/purple-teams#41]
A few weeks ago, some of my incoming Teams messages (strangely, not all) have started to come in with the string "Files sent:" appended directly to the end.

In Pidgin:
![image](https://github.com/EionRobb/purple-teams/assets/1655942/a572becd-a9c0-4711-9ec5-fda84733642b)

In Teams:
![image](https://github.com/EionRobb/purple-teams/assets/1655942/1105e174-34a3-4cea-a04d-20b9d1cfa42a)

Not sure if you have seen this before, if it might be related to anything about the "new" Teams client, or what.  This happens when there are no files sent of course.

**Comment by Scannow** [comment]
I noticed it too. It's related to the "new" client.

**Comment by greatquux** [comment]
I see the relevant lines in teams_messages.c in function teams_process_files_in_properties() that assumes that if the Teams message has the "files" property, it should, you know, contain files! Why would Teams lie to us? So it puts the "Files sent:" message and then goes through the array of files, except there aren't any.  So I guess the function would have to check the array length first and make sure there are actually some entries in there before writing "Files sent:".  I may attempt that, though I'd be using purely cargo cult methods to do so. :)
