### ISSUE TITLE
Strange header appearing in direct messages and group messages.

### ISSUE THREAD

**Issue by zoltan-dulac** [EionRobb/purple-teams#44]
I keep getting these strange things that look like HTTP headers in the message windows, for both Direct and Group Chat messages:

```
Project-Id-Version: Pidgin
Report-Msgid-Bugs-To: 
PO-Revision-Date: 2017-09-19 19:26+0000
Last-Translator: Richard Laager 
Language-Team: English (Canada) (http://www.transifex.com/pidgin/pidgin/language/en_CA/)
Language: en_CA
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
Plural-Forms: nplurals=2; plural=(n != 1);
```

Here is a screenshot of an example.

![image](https://github.com/EionRobb/purple-teams/assets/281398/aeb48d6d-615c-4a41-bf53-314b5866d09e)

I was going to look into this to see if I could fix myself, but I wanted to know if anyone here has seen this issue themselves and if they are solving it already.  If not, if you happen to know of the issue is, that will probably help me fix the issue faster.

Let me know.  Would love to contribute here.

**Comment by EionRobb** [comment]
Wow that's super weird! The translation system has picked up the en-CA translation header somehow! 

If you're looking at fixing, maybe start with looking at the en-CA.po file in Pidgin source and see how it compares to other po's? It might be something weird like we're trying to translate a blank string, and that gets picked up?

**Comment by EionRobb** [comment]
Also, not good that the contacts name hasn't come through and its only showing the "orgid:"😟

**Comment by zoltan-dulac** [comment]
@EionRobb I have opened up [another ticket about the `orgid:` issue](https://github.com/EionRobb/purple-teams/issues/45). 

As for the en_CA.po ... I see what you mean.   I have never dealt with this stuff before, so I am at a loss how it works.  I assume en_US doesn't have a .po file so this is not an issue with that locale, right?  I wonder if it happens in other locales like en_GB.  

I'll dig a bit when I get some time this week to see what is going on here.

Because you don't see this issue, I am curious why you don't see this issue?  What locale are you geo-located in? And where are the Teams servers you connect to?  Are you in the US?  I am located in Canada, so I guess that's why it's picking up the en_CA.po file stuff.

**Comment by EionRobb** [comment]
That last commit should fix it up, no more trying to translate a blank string :)  

I'm in NZ using the en_NZ translation, and haven't had the same issue.
