### ISSUE TITLE
Users I have never messaged directly in group chats show up as an `orgid:*` instead of the user's name.

### ISSUE THREAD

**Issue by zoltan-dulac** [EionRobb/purple-teams#45]
While looking at [this ticket about Strange header appearing in direct messages and group messages](https://github.com/EionRobb/purple-teams/issues/44#issuecomment-1850576244), @EionRobb mentioned that  it is [not good that the contacts name hasn't come through and its only showing the "orgid:"😟](https://github.com/EionRobb/purple-teams/issues/44#issuecomment-1850576244).

This issue seems to happen when I am in a group chat with users I have never messaged directly (i.e. one-on-one) before.  These users show up as `orgid:` users.

Here is a screenshot of the issue:

![image](https://github.com/EionRobb/purple-teams/assets/281398/4d9777e1-a1ad-452f-a856-2a7c61a0fa74)

**Comment by EionRobb** [comment]
I've added in a few changes to try resolve that (the aliases were being cleared out, and added in a new way to inject them into Pidgin's chat window surreptitiously).  Are you able to try with a recent build?

**Comment by EionRobb** [comment]
Hopefully working ok with the more recent build.  I've found a couple of extra places to pull the contact name from as well.  🤞 

Feel free to re-open this issue if it's still a problem
