### ISSUE TITLE
Show Bot-Names

### ISSUE THREAD

**Issue by ivy-rew** [EionRobb/purple-teams#5]
I use the 'github' bot for teams. It's quite nice to get notifications on changes @github 
Can you show bot-names in discussions?
![botName_asConversationName](https://user-images.githubusercontent.com/15085693/164254882-93f094f2-8741-407f-b972-a40664b2e5d8.png)

**Comment by EionRobb** [comment]
This should be available in https://github.com/EionRobb/purple-teams/commit/dae8ed81692304b86bd1e149f11b382ff0589f0c now :)

**Comment by ivy-rew** [comment]
This is so damn cool. Not only do I see the correct bot name, but user pictures are now fetched too. This makes the pidgin-teams integration much more personal :cupid: 

![teamsBots-andUsers](https://user-images.githubusercontent.com/15085693/164449774-47604859-7ff8-4223-8524-2b03826e09fa.png)

Thanks for your work @EionRobb . You make these pidgin-feature compliance with ms-teams look so easy. :1st_place_medal:
