### ISSUE TITLE
Pasted images come through as bad links

### ISSUE THREAD

**Issue by abwillis** [EionRobb/purple-teams#50]
When someone copies an image from (for instance) a web page and pastes it into a chat, instead of the image coming through a link is sent that looks like maybe it was supposed to be a link to the image but does not load (possibly because the browser is not authenticated).

Examples:
https://us-api.asm.skype.com/v1/objects/0-cus-d4-ccf19cf68d4826328a479839b751aaf1/views/imgpsh_fullsize
https://us-api.asm.skype.com/v1/objects/0-cus-d13-5249ec81d71440929b11be9daf7e2f96/views/imgpsh_fullsize
https://us-api.asm.skype.com/v1/objects/0-cus-d19-a0e68fdeb89bf05a0256f75307a4debf/views/imgpsh_fullsize

**Comment by abwillis** [comment]
Tested logging into teams via the browser that the links try to open in but still a blank page when click the link, which should rule out authentication being the issue.

**Comment by EionRobb** [comment]
Oh that's weird.  Normally logging into the browser first gets the links working.  Hmm.... We do try process the urls to make them the full size/original file, but do they work as https://us-api.asm.skype.com/v1/objects/0-cus-d4-ccf19cf68d4826328a479839b751aaf1/views/imgo or https://us-api.asm.skype.com/v1/objects/0-cus-d4-ccf19cf68d4826328a479839b751aaf1/views/imgt1 instead?

It should also be showing the image thumbnail inline too, if you're on Pidgin, but is the thumbnail not showing inline either?

**Comment by abwillis** [comment]
In Firefox, the pages are blank... in a Chromium based browser I get:
This page isn’t working If the problem continues, contact the site owner.
HTTP ERROR 401
There are no thumbnails, just the link.  And to avoid ambiguity, the links you provided did the same as the examples I had given.

**Comment by abwillis** [comment]
Actually, I just noticed that I am not quite accurate in my description.  There is the line with the link (which shows as "Click here to view full version") and a second entry from the sender that includes the sender information wherein that line is blank and then two more blank lines (three carriage returns it seems plus a space on the third line).

**Comment by abwillis** [comment]
![ksnip_20240327-084518](https://github.com/EionRobb/purple-teams/assets/4574703/4191ba0b-328e-42e8-a784-c5f679cac6eb)

**Comment by abwillis** [comment]
OK, this is embarrassing... I never thought to try the link in a Chromium based browser, wherein it works.

**Comment by EionRobb** [comment]
That's really annoying!  Thanks for coming back with more info.  I'll update the readme :)

I heard that they've recently made changes to allow Teams to work with Firefox, so hopefully works for non-chromium browsers too. 🤞
