### ISSUE TITLE
add ability to disable smileys per chat or person

### ISSUE THREAD

**Issue by abwillis** [EionRobb/purple-teams#58]
Hello, this is certainly low priority but it would be nice to be able to turn off smileys per chat.  We have an automated notification system setup for alerts such as an issue on a switch.  These often contain e:p which gets converted to e and the smiley with a tongue sticking out.  It is not a big deal, just a bit distracting.  I can highlight the text and disable smileys for selected text but it would be nice to be able to turn it off for that entire chat or by person.

**Comment by EionRobb** [comment]
Unfortunately, libpurple doesn't provide flags for deciding whether a message should be smileyified or not :(

I've been looking through the Pidgin source to see if there's even a hacky way for the Teams plugin to be able to remove smileys from a message/conversation, but I'm not seeing one - potentially I could try replacing all `:` with `&#x3a;` or `&#58;` and see if that tricks it, but it looks like the best way would be to have a Pidgin plugin that can do this on a per-conversation basis

**Comment by EionRobb** [comment]
Well, took longer than expected, but I wrote a plugin that will do that :) 
https://github.com/EionRobb/pidgin-conversation-smiley-disable

**Comment by abwillis** [comment]
Thank you very much... took me a moment to work out pkg-config as I haven't had to deal with it before (on opensuse I just had to change gtk-2.0 to gtk+-2.0) but once I worked it out it certainly cleans up my text nicely.

**Comment by EionRobb** [comment]
Whoops! I don't use Linux as my main system so I missed that. Thanks for letting me know

**Comment by abwillis** [comment]
I wasn't sure if it was just a distribution thing... I primarily use OS/2 and most of the things I build are on it so I certainly understand missing something on a less used system (I have QT available but not GTK or else I'd be building these on OS/2).
