### ISSUE TITLE
Cannot enable account for Personal

### ISSUE THREAD

**Issue by gabviv73** [EionRobb/purple-teams#59]
Hello, using Ubuntu Mantic, when I try to enable the Teams (Personal) account, it gives me error:

`AADSTS900023: Specified tenant identifier 'consumers' is neither a valid DNS name, nor a valid external domain. Trace ID: 4da00c11-17a0-472b-affe-295a5d10cf00 Correlation ID: 89a11e16-3ee2-477b-8807-34420857d677 Timestamp: 2024-07-18 08:48:12Z`

**Comment by EionRobb** [comment]
Whoops! Sorry about that. (I think I was trying to be too clever)

Is this the first time setting up the Personal account in Pidgin or has it been running happily before and now throws that error?

**Comment by EionRobb** [comment]
Just tried setting up a fresh Personal account and getting the same thing.  The above commit resolves for me, if you're able to try?

Sadly the login box no longer limits to just Personal logins, but better than not working at all.  (According to [the docs](https://learn.microsoft.com/en-us/entra/msal/java/getting-started/device-code-flow#constraints) this doesn't work for consumers/Personal accounts)

**Comment by gabviv73** [comment]
Yes, now it opens the browser windows and I can authenticate.
