### ISSUE TITLE
Repeating certificate accept dialog

### ISSUE THREAD

**Issue by palos-ba** [EionRobb/purple-teams#60]
Pidgin repeatedly displays dialog to accept certificate from these servers:
go.trouter.teams.microsoft.com, presence.teams.microsoft.com, login.microsoftonline.com
It spawns at least 3 of them at once, not in regular intervals, rather randomly.

I have checked Only use Websockets for message events, because without this setting I have strange behavior (multiple messages, not sent messages, high CPU usage), but this issue remains after unchecking it too.

Version: built from changeset bc2ba8a

**Comment by EionRobb** [comment]
Hmm. That's annoying. It could be that Pidgin doesn't trust the root certificate that Teams is using. I did see a recent news post thing from Microsoft saying that they were going to start using Azure root CAs instead of DigiCert, maybe related?

What OS/distro are you on?

If you're on Windows, can you try with the https://github.com/EionRobb/pidgin-win32-nss-cert-import plugin to see if using the system certificate store helps?

**Comment by palos-ba** [comment]
I'm on Fedora Linux, so that plugin is not for me... I know nothing about handling certs in Pidgin, but I tried to add the signing CA cert (CN=Microsoft Azure RSA TLS Issuing CA 03) to system truststore (/etc/pki/...), but it didn't help.

**Comment by EionRobb** [comment]
There might be a few more secrets revealed by the debug log. Can you open (from the Buddy List) Help -> Debug Window, then wait for it to happen again, and grab the debug output from around that time?

It should have a bunch of NSS info and error codes 🤞🏻

**Comment by palos-ba** [comment]
Uploaded [purple-debug.log](https://github.com/user-attachments/files/16871034/purple-debug.log) - events right after enabling teams account.
Strange thing is this message: Peer cert did NOT match cached
It looks like they (MS) are changing the certificates dynamically - or each backend server has own certificate...

**Comment by EionRobb** [comment]
```
(14:57:13) proxy: Connected to login.microsoftonline.com:443.
(14:57:13) nss: SSL version 3.4 using 256-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit TLS 1.3, Key Exchange: 384-bit TLS 1.3, Compression: NULL
Cipher Suite Name: TLS_AES_256_GCM_SHA384
(14:57:13) nss: subject=CN=stamp2.login.microsoftonline.com,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US issuer=CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US
(14:57:13) nss: subject=CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US issuer=CN=DigiCert Global Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(14:57:13) nss: subject=CN=DigiCert Global Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US issuer=CN=DigiCert Global Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(14:57:13) certificate/x509/tls_cached: Starting verify for login.microsoftonline.com
(14:57:13) certificate/x509/tls_cached: Checking for cached cert...
(14:57:13) certificate/x509/tls_cached: ...Found cached cert
(14:57:13) nss/x509: Loading certificate from /home/users/******/.purple/certificates/x509/tls_peers/login.microsoftonline.com
(14:57:13) certificate/x509/tls_cached: Peer cert did NOT match cached
(14:57:13) nss: CERT 0. CN=stamp2.login.microsoftonline.com,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US :
(14:57:13) nss:   ERROR -8179: SEC_ERROR_UNKNOWN_ISSUER
(14:57:16) certificate/x509/tls_cached: User ACCEPTED cert
Caching first in chain for future use as login.microsoftonline.com...
```

The interesting bit there is that it says there's an unknown issuer, that it doesn't know about one of the two DigiCert certificates there.

If you open https://stamp2.login.microsoftonline.com/ in a web browser (using the same SOCKS5 proxy), then view the certificates, does it say anything about an untrusted chain?  
Can you grab the "DigiCert Global Root CA" cert from https://www.digicert.com/kb/digicert-root-certificates.htm and save those certificates in that chain into your system certs folder and see if it resolves?

**Comment by palos-ba** [comment]
Server stamp2.login.microsoftonline.com is not in DNS, it is only in the CN attribute of the certificate. Connecting openssl to login.microsoftonline.com reveals the same issuer cert as I have in the system truststore (SubjectKeyIdentifier values are equal). Root certificate is not sent in the chain, but "DigiCert Global Root CA" has the same SubjectKeyIdentifier value as AuthorityKeyIdentifier in "DigiCert SHA2 Secure Server CA" (and cert from sent chain matches the one in my system truststore).
I suspect that some backend servers have moved to Azure CA and some still are on DigiCert. And DNS is doing round-robin (I see 8 IPv4 and 8 IPv6 addresses for the name). Quick look at directory ~/.purple/certificates/x509/tls_peers makes me think that pidgin/purple is caching the target server's certificate and yells about not matching ones (Peer cert did NOT match cached). But as I already wrote - I know nothing about code that handles certificates in pidgin/purple, it is only my guess... But if I'm right you have noting to do about it - pidgin/purple certificate handling is the main suspect and Microsoft the other ;-)

**Comment by EionRobb** [comment]
Yeah that all makes sense, and yeah not a plugin issue per se, but I'd still like to help! It might be a one-off temporary thing, but it might be an ongoing thing that others are experiencing too.

I'll see if there's a way for the plugin to override certificate caching for those domains. Unlikely but worth a shot.

Going down a tangent, with the proxy you're using, does it connect to a different IP each time? Can it be told to cache the IP to not give a different one out each time? Or does it have the option to act as an SSL middleman and provide it's own? Is it acting as the DNS server too?

**Comment by palos-ba** [comment]
Actually I can override the proxy setting and completely bypass the proxy (I'm in different environment now). But I think it is not the cause - see attached 
[purple-debug-noproxy.log](https://github.com/user-attachments/files/16886080/purple-debug-noproxy.log)
Name login.microsoftonline.com is resolved with different IP addresses (not every time, I think it is OS resolver caching thing).

**Comment by palos-ba** [comment]
Just before accepting new certificate I copied ~/.purple/certificates/x509/tls_peers/presence.teams.microsoft.com to backup and compared the new file with the backup (not raw files but cert details from them).

Before:
> Owner: CN=presence.teams.microsoft.com, O=Microsoft Corporation, L=Redmond, ST=WA, C=US
> Issuer: CN=Microsoft Azure RSA TLS Issuing CA 03, O=Microsoft Corporation, C=US
> Serial number: 3300750eef91d12206a672ad17000000750eef
> Valid from: Tue Jul 09 19:56:40 CEST 2024 until: Fri Jul 04 19:56:40 CEST 2025

After:
> Owner: CN=presence.teams.microsoft.com, O=Microsoft Corporation, L=Redmond, ST=WA, C=US
> Issuer: CN=Microsoft Azure RSA TLS Issuing CA 08, O=Microsoft Corporation, C=US
> Serial number: 3300421efeed465dcf961725dd000000421efe
> Valid from: Tue Jul 09 20:31:39 CEST 2024 until: Fri Jul 04 20:31:39 CEST 2025

Well, I don't think we can do anything with that mess (at least with pidgin/purple way of handling certificates as I know it - by caching target server certs)...

**Comment by EionRobb** [comment]
That's interesting when it's not going through the proxy:
```

(08:25:25) proxy: Connected to apac.ng.msg.teams.microsoft.com:443.
(08:25:26) nss: SSL version 3.3 using 256-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit RSA, Key Exchange: 384-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
(08:25:26) nss: subject=CN=msgapi.teams.microsoft.com,O=Microsoft Corporation,L=Redmond,ST=WA,C=US issuer=CN=Microsoft Azure RSA TLS Issuing CA 07,O=Microsoft Corporation,C=US
(08:25:26) nss: partial certificate chain
```
The "partial certificate chain" bit is saying that the server isn't sending the intermediate/root cert with the request. Some webservers are configured that they don't send an intermediate cert after they know the client has already connected once, to save bandwidth.

It might need a download of the "Microsoft Azure RSA TLS Issuing CA 07" cert into the system store?

Might just chuck that url through ssltest to see what it says, too.

**Comment by EionRobb** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=teams.microsoft.com&s=52.123.128.14&hideResults=on&ignoreMismatch=on seems to suggest that the server is sending the intermediate certificate. But the debug logs are saying otherwise :/

https://www.microsoft.com/pkiops/docs/repository.htm has the certs for download, and it mentions cross-signing the intermediate certs for two root CAs. Hmm.

Could you try getting the 07 cert into the tls_cached folder? If that works, then I'll have a look if there's a way for a plugin (maybe not this plugin but possibly a new one) to do better caching of intermediates.

**Comment by palos-ba** [comment]
I don't see any tls_cached directory on my system, only ~/.purple/certificates/x509/tls_peers - do I have to create ~/.purple/certificates/x509/tls_cached directory? What file name the intermediate cert is supposed to have?

**Comment by palos-ba** [comment]
This Pidgin binary is configured with argument --with-system-ssl-certs=/etc/pki/tls/certs, so I configured system to add all of the "Microsoft Azure RSA TLS Issuing CA 0X" to it. It didn't help, Pidgin is still asking and "nss:   ERROR -8179: SEC_ERROR_UNKNOWN_ISSUER" is in log.

And this time it is connecting to login.microsoftonline.com with cert signed by DigiCert:
> (11:52:51) proxy: Connecting to login.microsoftonline.com:443.
> (11:52:51) proxy: Connected to login.microsoftonline.com:443.
> (11:52:51) nss: SSL version 3.4 using 256-bit AES-GCM with 128-bit AEAD MAC
> Server Auth: 2048-bit TLS 1.3, Key Exchange: 384-bit TLS 1.3, Compression: NULL
> Cipher Suite Name: TLS_AES_256_GCM_SHA384
> (11:52:51) nss: subject=CN=stamp2.login.microsoftonline.com,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US **issuer=CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US**
> (11:52:51) nss: partial certificate chain
> (11:52:51) certificate/x509/tls_cached: Starting verify for login.microsoftonline.com
> (11:52:51) certificate/x509/tls_cached: Checking for cached cert...
> (11:52:51) certificate/x509/tls_cached: ...Not in cache
> (11:52:51) nss/x509: Loading certificate from /etc/pki/tls/certs/ca-bundle.crt
> ...
> (11:52:51) nss: **Trusting CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US**
> (11:52:51) certificate/x509/ca: Loaded DigiCert SHA2 Secure Server CA from /etc/pki/tls/certs/ca-bundle.crt
> ...
> (11:52:51) certificate/x509/ca: Lazy init completed.
> (11:52:51) nss: CERT 0. CN=stamp2.login.microsoftonline.com,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US :
> (11:52:51) nss:   **ERROR -8179: SEC_ERROR_UNKNOWN_ISSUER**
I don't understand why...

**Comment by EionRobb** [comment]
Someone jumped into the #pidgin irc room with https://issues.imfreedom.org/issue/PIDGIN-17886/Certificate-verification-errors-with-NSS-3.103 which looks plausible!

**Comment by EionRobb** [comment]
I wonder if there's a way to shoehorn that patch into a plugin....... hmm
