### ISSUE TITLE
Enter code to allow access

### ISSUE THREAD

**Issue by Mandarancio** [EionRobb/purple-teams#62]
Hi!
First I would like to thank you very much for your work!

Unfortunatly I have an issue, when trying to login with my user I get to this page

![image](https://github.com/user-attachments/assets/a2a84161-9902-40df-87ac-4b01343c6de0)

But I do not have any idea where to find the code! 

Thank you very much in advance!
Best regards,
Martino

**Comment by EionRobb** [comment]
Oh! There should be a popup window in Pidgin with the code, eg 
![image](https://github.com/user-attachments/assets/2ce76f15-97bb-4cbc-a0ae-20c0c50a127d)
If you're using bitlbee it'll come through as a DM.

It might have opened up behind other windows, and it only hangs around for a minute before it closes and the buddy list shows a connection error.

**Comment by Mandarancio** [comment]
Perfect! sorry for the stupid question! It was indeed hidden!
