### ISSUE TITLE
Problem while running sudo make install

### ISSUE THREAD

**Issue by EthanHarp** [EionRobb/purple-teams#7]
make: *** No rule to make target 'theme', needed by 'install-theme'. Stop

I get this message everytime I run sudo make install

**Comment by EionRobb** [comment]
Oh whoops. That must have hung over from the skypeweb plugin. If you don't race me to it, you can remove the theme stuff from the Makefile or you can copy the plugin manually with `cp libteams.so ~/.purple/plugins/`

**Comment by EthanHarp** [comment]
Did that and it let me get to the login page so thank you, after going through the login process I am now getting the error of "failed getting skype token(alt)" any advice?

**Comment by EionRobb** [comment]
It opened in the browser and got you to copy paste the url into the popup? Is this a Teams for School/Work account? 

Might need to grab a debug log to see what's going on if the above is the case. From the buddy list, Help->Debug Window as you reconnect to the account. 

Just be careful with the log through. The plugin is pretty fresh and i haven't gone through and made sure that nothing sensitive is showing in the logs yet. Please check if over to make sure there's nothing evil like refresh tokens or passwords showing in there before attaching. If you want, you can email it to me direct.

**Comment by EthanHarp** [comment]
Yep copy and pasted url into pop, and it's a school account. I just emailed you the logs from the debug window, appreciate the help.

**Comment by EionRobb** [comment]
You mentioned via email that things are working better now.  Is it ok if I close this issue?

**Comment by gzuaps** [comment]
Hi @EionRobb ,
I still have to remove the install-theme stuff from the Makefile to build.
Can it be removed permanently in the repo or is it required for something?
Thanks

**Comment by EionRobb** [comment]
Whoops, forgot about the theme thing.  https://github.com/EionRobb/purple-teams/commit/ba734e6a1314f58d4ca58f37c2537d6ba403fe16 should deal with it :)

In the future, happy to take PRs to fix stuff :)
