### ISSUE TITLE
Upload/post images to chat

### ISSUE THREAD

**Issue by ivy-rew** [EionRobb/purple-teams#9]
I use the file-upload feature of ms-teams quit frequently. In most occasions just to share or emphasize a particular issue with a screenshot. So I have no need for fancy one-drive integration or something. But selecting a local image from disk and share it with a chat user would be really nice and fits into the standard pidgin feature-set.

Is it a big thing to provide image-upload with the purple-teams plugin?
![teamsUploadFiles](https://user-images.githubusercontent.com/15085693/166869795-8a51ae12-5b6b-4aa2-9a74-1a4721600aff.png)
![pidginImageUpload](https://user-images.githubusercontent.com/15085693/166869801-2c2b6d4d-b66c-4fe0-b820-bf32e8196703.png)

**Comment by EionRobb** [comment]
Hopefully that commit does the trick for you :)

There's a bit of a weirdness with image display sizing for other people that I'm not quite sure how to workaround just yet (we need to send image height/width, but there's no api in libpurple that can tell us that info)

**Comment by ivy-rew** [comment]
Yes, you did it @EionRobb . Great job :1st_place_medal: 

I've just posted a log-output and it worked flawlessly by using purple-teams. Later I've opened ms-teams to verify my input. And it looks as expected. So the assumed image size seems to work ;)
![imagePostingWorks](https://user-images.githubusercontent.com/15085693/167356625-409cb850-fc52-4012-bbaa-6cf79df7fa76.png)
